#!/nix/store/vs6d2fjkl4kb3jb7rwibsd76k9v2n4xy-bash-4.4-p23/bin/sh

sxhkd &
nm-applet &

bspc monitor -d term web chat code other persistent

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled
