#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export TERMINAL="xterm"

export NVM_DIR=$HOME/.nvm
source ~/.zprezto/runcoms/lazy-load.sh
lazyload nvm ~/.nvm/versions/node /usr/share/nvm/nvm.sh
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export GOPATH=~/projects/go
export PATH="$PATH:$GOPATH/bin"

export PYENV_ROOT="$HOME/.pyenv"
lazy_pyenvcallback() {
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
}
lazy_rbenvcallback() {
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
}
lazyload pyenv ~/.pyenv/versions -- lazy_pyenvcallback
lazyload rbenv ~/.rbenv/versions -- lazy_rbenvcallback

export RUST_SRC_PATH="$HOME/rust/src"

export PATH="$HOME/.local/bin/:$PATH"

export PATH="$HOME/.emacs.d/bin/:$PATH"

export PATH="$HOME/.cabal/bin:$PATH"

export LIBVIRT_DEFAULT_URI=qemu:///system
